import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers, ReduxProvider } from "./providers";
import { CssBaseline } from "@mui/material";
import Header from "./_components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <CssBaseline />
          <Header/>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
